modLoader="javafml"
loaderVersion="${loader_version_range}"

license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="Axedgaming, Furti Two"
    description='''
    An addon for Farmer's Delight based around adding culinary content to the end!
    '''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="farmersdelight"
    type="required"
    versionRange="1.21.1-1.2.10"
    ordering="NONE"
    side="BOTH"